### ISSUE TITLE
Using Ant Design Variables in Styled Components

### ISSUE THREAD

**Issue by hshoja** [DocSpring/craco-antd#71]
I would like to be able to access the Ant Design variables (which are written in Less) within a styled component. Something like this:
```js
const StyledButton = styled(Button)`
  background-color: @primary-color
`
```

how can I achieve this?

**Comment by floatrx** [comment]
Try use native css variable instead.

### Map with less variables:
```less
:root {
   --primary-color: var(@primary-color);
   // other global variables
}
```

```jsx
const StyledButton = styled(Button)`
  background-color: --primary-color;
`
```
